// Collection-specific tiles configuration for ScrollStack component
// This file defines which specific products should be displayed as tiles for each collection

const BASE_URL = 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master';

export const collectionTiles = {
  'regular-tiles': [
    {
      id: 'rt-001',
      name: 'Amba White',
      image: '/assets/regular-tiles/AMBAWHITE-1.jpg',
      thumbnailImages: ['/assets/regular-tiles/AMBAWHITE-1.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-002',
      name: 'Bengal White',
      image: '/assets/regular-tiles/BENGALWHITE-1.jpg',
      thumbnailImages: ['/assets/regular-tiles/BENGALWHITE-1.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-003',
      name: 'Black Forest',
      image: '/assets/regular-tiles/BLACKFOREST-1.jpg',
      thumbnailImages: ['/assets/regular-tiles/BLACKFOREST-1.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-004',
      name: 'Black Galaxy',
      image: '/assets/regular-tiles/BLACKGALAXY.jpg',
      thumbnailImages: ['/assets/regular-tiles/BLACKGALAXY.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-005',
      name: 'Coffee Brown',
      image: '/assets/regular-tiles/COFFEEBROWN.jpg',
      thumbnailImages: ['/assets/regular-tiles/COFFEEBROWN.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-006',
      name: 'Absolute Black',
      image: '/assets/regular-tiles/absolute-black-1.png',
      thumbnailImages: ['/assets/regular-tiles/absolute-black-1.png'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-007',
      name: 'Colombo Juprana',
      image: '/assets/regular-tiles/colombo-juprana.jpg',
      thumbnailImages: ['/assets/regular-tiles/colombo-juprana.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-008',
      name: 'Indian Dakota',
      image: '/assets/regular-tiles/indian-dakota.jpg',
      thumbnailImages: ['/assets/regular-tiles/indian-dakota.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-009',
      name: 'Ivory Brown',
      image: '/assets/regular-tiles/ivorybrown.jpg',
      thumbnailImages: ['/assets/regular-tiles/ivorybrown.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-010',
      name: 'Ivory Fantasy',
      image: '/assets/regular-tiles/ivoryfantasy.jpg',
      thumbnailImages: ['/assets/regular-tiles/ivoryfantasy.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-011',
      name: 'Kashmir Cream',
      image: '/assets/regular-tiles/kashmir-cream.jpg',
      thumbnailImages: ['/assets/regular-tiles/kashmir-cream.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-012',
      name: 'Kashmir White',
      image: '/assets/regular-tiles/kashmir-white.jpg',
      thumbnailImages: ['/assets/regular-tiles/kashmir-white.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-013',
      name: 'Multi Color',
      image: '/assets/regular-tiles/multi-color.png',
      thumbnailImages: ['/assets/regular-tiles/multi-color.png'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-014',
      name: 'New Kashmir Cream',
      image: '/assets/regular-tiles/new-kashmir-cream-calibrated-tiles.jpg',
      thumbnailImages: ['/assets/regular-tiles/new-kashmir-cream-calibrated-tiles.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-015',
      name: 'Paradiso Bash',
      image: '/assets/regular-tiles/paradiso-bash.jpg',
      thumbnailImages: ['/assets/regular-tiles/paradiso-bash.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-016',
      name: 'Paradiso Classic',
      image: '/assets/regular-tiles/paradiso-classic1.jpg',
      thumbnailImages: ['/assets/regular-tiles/paradiso-classic1.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-017',
      name: 'Steel Grey',
      image: '/assets/regular-tiles/steel-grey.png',
      thumbnailImages: ['/assets/regular-tiles/steel-grey.png'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-018',
      name: 'Tan Brown',
      image: '/assets/regular-tiles/tan-brown.png',
      thumbnailImages: ['/assets/regular-tiles/tan-brown.png'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    },
    {
      id: 'rt-019',
      name: 'Viscount White Tiles',
      image: '/assets/regular-tiles/viscount-white-tiles.jpg',
      thumbnailImages: ['/assets/regular-tiles/viscount-white-tiles.jpg'],
      collection: 'Regular Tiles',
      description: 'Premium natural granite tile.',
      tags: ['granite', 'natural', 'premium']
    }
  ],
  
  // 'regular-tiles': [
  //   {
  //     id: 'rt-001',
  //     name: 'Astoria',
  //     image: `${BASE_URL}/Regular-tiles-webp/ASTORIAA.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/ASTORIAA.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Natural granite tile with premium finish.',
  //     color: 'Mixed',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['granite', 'natural', 'premium'],
  //   },
  //   {
  //     id: 'rt-002',
  //     name: 'Bengal White',
  //     image: `${BASE_URL}/Regular-tiles-webp/BENGAL WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BENGAL WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Classic white Bengal granite with subtle patterning.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['white', 'granite', 'classic'],
  //   },
  //   {
  //     id: 'rt-003',
  //     name: 'Bianco Antico',
  //     image: `${BASE_URL}/Regular-tiles-webp/BIANCO ANTICO.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BIANCO ANTICO.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Elegant white granite with warm tones.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['white', 'granite', 'elegant'],
  //   },
  //   {
  //     id: 'rt-004',
  //     name: 'Bianco Tiffone',
  //     image: `${BASE_URL}/Regular-tiles-webp/BIANCO TIFFONE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BIANCO TIFFONE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Bright white granite with fine grain texture.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['white', 'granite', 'bright'],
  //   },
  //   {
  //     id: 'rt-005',
  //     name: 'Black Forest',
  //     image: `${BASE_URL}/Regular-tiles-webp/BLACK FOREST.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BLACK FOREST.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Deep black granite with a forest-like natural pattern.',
  //     color: 'Black',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['black', 'granite', 'dark'],
  //   },
  //   {
  //     id: 'rt-006',
  //     name: 'Black Pearl',
  //     image: `${BASE_URL}/Regular-tiles-webp/BLACK PEARL.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BLACK PEARL.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Lustrous black granite with pearl-like shimmer.',
  //     color: 'Black',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['black', 'granite', 'luxury'],
  //   },
  //   {
  //     id: 'rt-007',
  //     name: 'Coffee Brown',
  //     image: `${BASE_URL}/Regular-tiles-webp/COFFEE BROWN.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COFFEE BROWN.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Rich coffee brown granite for warm interiors.',
  //     color: 'Brown',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops'],
  //     tags: ['brown', 'granite', 'warm'],
  //   },
  //   {
  //     id: 'rt-008',
  //     name: 'Colombo Juprana',
  //     image: `${BASE_URL}/Regular-tiles-webp/COLOMBO JUPRANA.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLOMBO JUPRANA.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Versatile Juprana granite from Colombo with mixed tones.',
  //     color: 'Mixed',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['granite', 'natural', 'mixed'],
  //   },
  //   {
  //     id: 'rt-009',
  //     name: 'Colonial Cream',
  //     image: `${BASE_URL}/Regular-tiles-webp/COLONIAL CREAM.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLONIAL CREAM.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Warm cream granite with colonial elegance.',
  //     color: 'Cream',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['cream', 'granite', 'warm'],
  //   },
  //   {
  //     id: 'rt-010',
  //     name: 'Colonial Gold',
  //     image: `${BASE_URL}/Regular-tiles-webp/COLONIAL GOLD.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLONIAL GOLD.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Golden granite with rich colonial character.',
  //     color: 'Gold',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['gold', 'granite', 'premium'],
  //   },
  //   {
  //     id: 'rt-011',
  //     name: 'Colonial White',
  //     image: `${BASE_URL}/Regular-tiles-webp/COLONIAL WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLONIAL WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Crisp white colonial granite for timeless spaces.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['white', 'granite', 'classic'],
  //   },
  //   {
  //     id: 'rt-012',
  //     name: 'Gibli Gold',
  //     image: `${BASE_URL}/Regular-tiles-webp/GIBLI GOLD.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/GIBLI GOLD.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Radiant gold granite with natural Gibli character.',
  //     color: 'Gold',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops'],
  //     tags: ['gold', 'granite', 'radiant'],
  //   },
  //   {
  //     id: 'rt-013',
  //     name: 'Gibli',
  //     image: `${BASE_URL}/Regular-tiles-webp/GIBLI.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/GIBLI.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Natural Gibli granite with organic patterns.',
  //     color: 'Mixed',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['granite', 'natural'],
  //   },
  //   {
  //     id: 'rt-014',
  //     name: 'Hassan Green',
  //     image: `${BASE_URL}/Regular-tiles-webp/HASSAN GREEN.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/HASSAN GREEN.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Distinctive green granite from Hassan, Karnataka.',
  //     color: 'Green',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['green', 'granite', 'unique'],
  //   },
  //   {
  //     id: 'rt-015',
  //     name: 'Himalayan Blue',
  //     image: `${BASE_URL}/Regular-tiles-webp/HIMALAYAN BLUE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/HIMALAYAN BLUE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Rare blue granite inspired by the Himalayan range.',
  //     color: 'Blue',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['blue', 'granite', 'rare'],
  //   },
  //   {
  //     id: 'rt-016',
  //     name: 'Imperial Gold',
  //     image: `${BASE_URL}/Regular-tiles-webp/IMPERIAL GOLD.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/IMPERIAL GOLD.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Majestic gold granite for imperial interiors.',
  //     color: 'Gold',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['gold', 'granite', 'luxury'],
  //   },
  //   {
  //     id: 'rt-017',
  //     name: 'Imperial White',
  //     image: `${BASE_URL}/Regular-tiles-webp/IMPERIAL WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/IMPERIAL WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Pure white imperial granite with refined beauty.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['white', 'granite', 'premium'],
  //   },
  //   {
  //     id: 'rt-018',
  //     name: 'Indian Juprana 2',
  //     image: `${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA 2.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA 2.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Second variety of the popular Indian Juprana granite.',
  //     color: 'Mixed',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['granite', 'natural', 'indian'],
  //   },
  //   {
  //     id: 'rt-019',
  //     name: 'Indian Juprana',
  //     image: `${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Classic Indian Juprana granite with bold veining.',
  //     color: 'Mixed',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['granite', 'natural', 'indian'],
  //   },
  //   {
  //     id: 'rt-020',
  //     name: 'Ivory Brown',
  //     image: `${BASE_URL}/Regular-tiles-webp/IVORY BROWN.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/IVORY BROWN.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Soft ivory and brown granite with natural warmth.',
  //     color: 'Brown',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['ivory', 'brown', 'granite'],
  //   },
  //   {
  //     id: 'rt-021',
  //     name: 'Kashmir Cream',
  //     image: `${BASE_URL}/Regular-tiles-webp/KASHMIR CREAM.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KASHMIR CREAM.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Creamy Kashmir granite with delicate mineral inclusions.',
  //     color: 'Cream',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops'],
  //     tags: ['cream', 'granite', 'kashmir'],
  //   },
  //   {
  //     id: 'rt-022',
  //     name: 'Kashmir Gold',
  //     image: `${BASE_URL}/Regular-tiles-webp/KASHMIR GOLD.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KASHMIR GOLD.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Royal gold Kashmir granite for luxurious surfaces.',
  //     color: 'Gold',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['gold', 'granite', 'kashmir'],
  //   },
  //   {
  //     id: 'rt-023',
  //     name: 'Kashmir White',
  //     image: `${BASE_URL}/Regular-tiles-webp/KASHMIR WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KASHMIR WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Pristine white Kashmir granite, globally renowned.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['white', 'granite', 'kashmir'],
  //   },
  //   {
  //     id: 'rt-024',
  //     name: 'Kuppam Green',
  //     image: `${BASE_URL}/Regular-tiles-webp/KUPPAM GREEN.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KUPPAM GREEN.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Vibrant green granite from Kuppam, Andhra Pradesh.',
  //     color: 'Green',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['green', 'granite', 'vibrant'],
  //   },
  //   {
  //     id: 'rt-025',
  //     name: 'Matrix',
  //     image: `${BASE_URL}/Regular-tiles-webp/MATRIX.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MATRIX.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Dynamic matrix-patterned granite for modern spaces.',
  //     color: 'Mixed',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['granite', 'modern', 'unique'],
  //   },
  //   {
  //     id: 'rt-026',
  //     name: 'Meera White',
  //     image: `${BASE_URL}/Regular-tiles-webp/MEERA WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MEERA WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Soft white Meera granite with delicate patterns.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops'],
  //     tags: ['white', 'granite', 'soft'],
  //   },
  //   {
  //     id: 'rt-027',
  //     name: 'Mist Black',
  //     image: `${BASE_URL}/Regular-tiles-webp/MIST BLACK.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MIST BLACK.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Black granite with misty mineral highlights.',
  //     color: 'Black',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['black', 'granite', 'dark'],
  //   },
  //   {
  //     id: 'rt-028',
  //     name: 'Moon White',
  //     image: `${BASE_URL}/Regular-tiles-webp/MOON WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MOON WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Luminous white granite with moon-like texture.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops'],
  //     tags: ['white', 'granite', 'luminous'],
  //   },
  //   {
  //     id: 'rt-029',
  //     name: 'Multi Colour',
  //     image: `${BASE_URL}/Regular-tiles-webp/MULTI COLOUR.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MULTI COLOUR.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Vibrant multi-colour granite for expressive designs.',
  //     color: 'Multi',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['multicolour', 'granite', 'vibrant'],
  //   },
  //   {
  //     id: 'rt-030',
  //     name: 'New Kashmir Cream',
  //     image: `${BASE_URL}/Regular-tiles-webp/NEW KASHMIR CREAM.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW KASHMIR CREAM.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Updated Kashmir Cream granite with refined texture.',
  //     color: 'Cream',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops'],
  //     tags: ['cream', 'granite', 'kashmir'],
  //   },
  //   {
  //     id: 'rt-031',
  //     name: 'New Kashmir Gold',
  //     image: `${BASE_URL}/Regular-tiles-webp/NEW KASHMIR GOLD.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW KASHMIR GOLD.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Contemporary Kashmir Gold granite with deep luster.',
  //     color: 'Gold',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['gold', 'granite', 'kashmir'],
  //   },
  //   {
  //     id: 'rt-032',
  //     name: 'New Kashmir White',
  //     image: `${BASE_URL}/Regular-tiles-webp/NEW KASHMIR WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW KASHMIR WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Refreshed Kashmir White granite, timelessly beautiful.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['white', 'granite', 'kashmir'],
  //   },
  //   {
  //     id: 'rt-033',
  //     name: 'New Meera White',
  //     image: `${BASE_URL}/Regular-tiles-webp/NEW MEERA WHITE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW MEERA WHITE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Upgraded Meera White granite with cleaner finish.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops'],
  //     tags: ['white', 'granite', 'meera'],
  //   },
  //   {
  //     id: 'rt-034',
  //     name: 'Paradiso Bash',
  //     image: `${BASE_URL}/Regular-tiles-webp/PARADISO BASH.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/PARADISO BASH.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Bold Paradiso Bash granite with striking purple tones.',
  //     color: 'Purple',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['purple', 'granite', 'paradiso'],
  //   },
  //   {
  //     id: 'rt-035',
  //     name: 'Paradiso Classic',
  //     image: `${BASE_URL}/Regular-tiles-webp/PARADISO CLASSIC.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/PARADISO CLASSIC.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Classic Paradiso granite with signature mineral patterns.',
  //     color: 'Purple',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['purple', 'granite', 'classic'],
  //   },
  //   {
  //     id: 'rt-036',
  //     name: 'Parana Boardux',
  //     image: `${BASE_URL}/Regular-tiles-webp/PARANA BOARDUX.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/PARANA BOARDUX.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Parana Boardux granite with distinctive grain.',
  //     color: 'Mixed',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['granite', 'natural', 'parana'],
  //   },
  //   {
  //     id: 'rt-037',
  //     name: 'Regal Black',
  //     image: `${BASE_URL}/Regular-tiles-webp/REGAL BLACK.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/REGAL BLACK.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Commanding Regal Black granite for sophisticated spaces.',
  //     color: 'Black',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['black', 'granite', 'regal'],
  //   },
  //   {
  //     id: 'rt-038',
  //     name: 'River White 1',
  //     image: `${BASE_URL}/Regular-tiles-webp/RIVER WHITE 1.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/RIVER WHITE 1.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Serene River White granite with flowing veins.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['white', 'granite', 'river'],
  //   },
  //   {
  //     id: 'rt-039',
  //     name: 'River White 2',
  //     image: `${BASE_URL}/Regular-tiles-webp/RIVER WHITE 2.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/RIVER WHITE 2.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Second variety of River White granite with unique flow.',
  //     color: 'White',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['white', 'granite', 'river'],
  //   },
  //   {
  //     id: 'rt-040',
  //     name: 'Royal Ivory',
  //     image: `${BASE_URL}/Regular-tiles-webp/ROYAL IVORY.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/ROYAL IVORY.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Luxurious ivory granite fit for royal interiors.',
  //     color: 'Ivory',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['ivory', 'granite', 'luxury'],
  //   },
  //   {
  //     id: 'rt-041',
  //     name: 'Sapphire Blue',
  //     image: `${BASE_URL}/Regular-tiles-webp/SAPPHIRE BLUE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/SAPPHIRE BLUE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Deep sapphire blue granite for elegant statements.',
  //     color: 'Blue',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['blue', 'granite', 'sapphire'],
  //   },
  //   {
  //     id: 'rt-042',
  //     name: 'Spice Black',
  //     image: `${BASE_URL}/Regular-tiles-webp/SPICE BLACK.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/SPICE BLACK.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Rich Spice Black granite with warm undertones.',
  //     color: 'Black',
  //     finish: 'Polished',
  //     useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
  //     tags: ['black', 'granite', 'spice'],
  //   },
  //   {
  //     id: 'rt-043',
  //     name: 'Steel Grey',
  //     image: `${BASE_URL}/Regular-tiles-webp/STEEL GREY.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/STEEL GREY.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Industrial-chic Steel Grey granite for modern aesthetics.',
  //     color: 'Grey',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['grey', 'granite', 'modern'],
  //   },
  //   {
  //     id: 'rt-044',
  //     name: 'Tan Brown',
  //     image: `${BASE_URL}/Regular-tiles-webp/TAN BROWN.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/TAN BROWN.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Warm Tan Brown granite with natural earthy tones.',
  //     color: 'Brown',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['brown', 'granite', 'tan'],
  //   },
  //   {
  //     id: 'rt-045',
  //     name: 'Ultimate Black',
  //     image: `${BASE_URL}/Regular-tiles-webp/ULTIMATE BLACK.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/ULTIMATE BLACK.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Absolute deep black granite for bold design statements.',
  //     color: 'Black',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
  //     tags: ['black', 'granite', 'bold'],
  //   },
  //   {
  //     id: 'rt-046',
  //     name: 'Viscount Waves',
  //     image: `${BASE_URL}/Regular-tiles-webp/VISCOUNT WAVES.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/VISCOUNT WAVES.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Elegant Viscount granite with wave-like natural patterns.',
  //     color: 'Grey',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
  //     tags: ['grey', 'granite', 'viscount'],
  //   },
  //   {
  //     id: 'rt-047',
  //     name: 'Vizag Blue',
  //     image: `${BASE_URL}/Regular-tiles-webp/VIZAG BLUE.webp`,
  //     thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/VIZAG BLUE.webp`],
  //     collection: 'Regular Tiles',
  //     description: 'Striking Vizag Blue granite from Visakhapatnam.',
  //     color: 'Blue',
  //     finish: 'Polished',
  //     useCase: ['Flooring', 'Wall Cladding'],
  //     tags: ['blue', 'granite', 'vizag'],
  //   },
  // ],

  'granite-slabs': [
    {
      id: 'gs-001',
      name: 'Absolute Black',
      image: `${BASE_URL}/Granite-Slabs/ABSOLUTE BLACK 4502,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/ABSOLUTE BLACK 4502,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'The definitive jet-black granite slab for premium installations.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['black', 'granite', 'absolute'],
    },
    {
      id: 'gs-002',
      name: 'Black Pearl',
      image: `${BASE_URL}/Granite-Slabs/BLACK PEARL 206,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/BLACK PEARL 206,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Black Pearl granite slab with iridescent mineral highlights.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['black', 'granite', 'pearl'],
    },
    {
      id: 'gs-003',
      name: 'Blue Pearl',
      image: `${BASE_URL}/Granite-Slabs/BLUE PEARL 4271,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/BLUE PEARL 4271,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Striking Blue Pearl granite slab with labradorite shimmer.',
      color: 'Blue',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['blue', 'granite', 'pearl'],
    },
    {
      id: 'gs-004',
      name: 'Coffee Brown',
      image: `${BASE_URL}/Granite-Slabs/COFFEE BROWN 111,3CM,10 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/COFFEE BROWN 111,3CM,10 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Rich Coffee Brown granite slab for warm interiors.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['brown', 'granite', 'coffee'],
    },
    {
      id: 'gs-005',
      name: 'Ivory Brown',
      image: `${BASE_URL}/Granite-Slabs/IVORY BROWN 799,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/IVORY BROWN 799,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Warm Ivory Brown granite slab with natural elegance.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['ivory', 'brown', 'granite'],
    },
    {
      id: 'gs-006',
      name: 'Kashmir Cream',
      image: `${BASE_URL}/Granite-Slabs/KASHMIR CREAM 1244,2CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/KASHMIR CREAM 1244,2CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Kerala\'s finest Kashmir Cream granite slab.',
      color: 'Cream',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['cream', 'granite', 'kashmir'],
    },
    {
      id: 'gs-007',
      name: 'Kuppam Green',
      image: `${BASE_URL}/Granite-Slabs/KUPPAM GREEN 103,2CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/KUPPAM GREEN 103,2CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Vibrant Kuppam Green granite slab with distinctive hue.',
      color: 'Green',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['green', 'granite', 'kuppam'],
    },
    {
      id: 'gs-008',
      name: 'Multi Colour',
      image: `${BASE_URL}/Granite-Slabs/MULTI COLOUR 3021,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/MULTI COLOUR 3021,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Bold multi-colour granite slab for expressive design.',
      color: 'Multi',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['multicolour', 'granite', 'vibrant'],
    },
    {
      id: 'gs-009',
      name: 'New Kashmir Cream',
      image: `${BASE_URL}/Granite-Slabs/NEW KASHMIR CREAM 2211,3CM,2 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW KASHMIR CREAM 2211,3CM,2 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Updated Kashmir Cream granite slab with enhanced finish.',
      color: 'Cream',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['cream', 'granite', 'kashmir'],
    },
    {
      id: 'gs-010',
      name: 'New Kashmir White',
      image: `${BASE_URL}/Granite-Slabs/NEW KASHMIR WHITE 536,3CM,40 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW KASHMIR WHITE 536,3CM,40 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'New Kashmir White granite slab with pure bright finish.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['white', 'granite', 'kashmir'],
    },
    {
      id: 'gs-011',
      name: 'New Meera White (Close Up)',
      image: `${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 104,3CM,30 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 104,3CM,30 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Close-up view of New Meera White granite slab.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['white', 'granite', 'meera'],
    },
    {
      id: 'gs-012',
      name: 'New Meera White',
      image: `${BASE_URL}/Granite-Slabs/NEW%20MEERA%20WHITE%20104%2C3CM%2C30.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW%20MEERA%20WHITE%20104%2C3CM%2C30.webp`],
      collection: 'Granite Slabs',
      description: 'Full slab view of New Meera White granite.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['white', 'granite', 'meera'],
    },
    {
      id: 'gs-013',
      name: 'New Meera White 91',
      image: `${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 91,3CM,10 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 91,3CM,10 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'New Meera White granite slab, variety 91.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['white', 'granite', 'meera'],
    },
    {
      id: 'gs-014',
      name: 'Paradiso Bash',
      image: `${BASE_URL}/Granite-Slabs/PARADISO BASH 23A,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/PARADISO BASH 23A,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Paradiso Bash granite slab with rich purple undertones.',
      color: 'Purple',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['purple', 'granite', 'paradiso'],
    },
    {
      id: 'gs-015',
      name: 'Paradiso Classic',
      image: `${BASE_URL}/Granite-Slabs/PARADISO CLASSIC 1044,5CM,10 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/PARADISO CLASSIC 1044,5CM,10 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Paradiso Classic granite slab with signature veining.',
      color: 'Purple',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['purple', 'granite', 'classic'],
    },
    {
      id: 'gs-016',
      name: 'Sapphire Blue',
      image: `${BASE_URL}/Granite-Slabs/SAPPHIRE BLUE 1501,3CM,25 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/SAPPHIRE BLUE 1501,3CM,25 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Deep Sapphire Blue granite slab for elegant installations.',
      color: 'Blue',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['blue', 'granite', 'sapphire'],
    },
    {
      id: 'gs-017',
      name: 'Silver Waves',
      image: `${BASE_URL}/Granite-Slabs/SILVER WAVES 112,3CM,25 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/SILVER WAVES 112,3CM,25 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Silver Waves granite slab with shimmering wave patterns.',
      color: 'Grey',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['silver', 'grey', 'granite'],
    },
    {
      id: 'gs-018',
      name: 'Steel Grey',
      image: `${BASE_URL}/Granite-Slabs/STEEL GREY 307,2CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/STEEL GREY 307,2CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Sleek Steel Grey granite slab for contemporary spaces.',
      color: 'Grey',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['grey', 'granite', 'steel'],
    },
    {
      id: 'gs-019',
      name: 'Tan Brown',
      image: `${BASE_URL}/Granite-Slabs/TAN BROWN 101,3CM,25 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/TAN BROWN 101,3CM,25 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Warm Tan Brown granite slab with natural earthy tones.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['brown', 'granite', 'tan'],
    },
    {
      id: 'gs-020',
      name: 'Viscount White',
      image: `${BASE_URL}/Granite-Slabs/VISCOUNT WHITE 1024,2CM,55 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/VISCOUNT WHITE 1024,2CM,55 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Viscount White granite slab with flowing crystalline patterns.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['white', 'grey', 'granite'],
    },
  ],
  'exotics-exclusive': 
  [
    { id: 'ee-001', name: 'Blue Deep', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/BLUE%20DEEP%20BL%2028847A%20BDL%20109429.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/BLUE%20DEEP%20BL%2028847A%20BDL%20109429.webp'], collection: 'Exotics & Exclusives', description: 'Blue Deep exotic surface.', color: 'Blue', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['blue', 'exotic'] },
    { id: 'ee-002', name: 'Brilliant Grey Honed', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/BRILLIANT%20GREY%20Honed%20BL%2081-21%20BDL%209429.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/BRILLIANT%20GREY%20Honed%20BL%2081-21%20BDL%209429.webp'], collection: 'Exotics & Exclusives', description: 'Brilliant Grey Honed exotic surface.', color: 'Grey', finish: 'Honed', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['grey', 'exotic'] },
    { id: 'ee-003', name: 'Calacata Matarazzo Honed', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CALACATA%20MATARAZZO%20Honed%20BL%2009-22%20BDL%2010423.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CALACATA%20MATARAZZO%20Honed%20BL%2009-22%20BDL%2010423.webp'], collection: 'Exotics & Exclusives', description: 'Calacata Matarazzo Honed exotic surface.', color: 'White', finish: 'Honed', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['white', 'exotic'] },
    { id: 'ee-004', name: 'Cristal Cartier', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CRISTAL%20CARTIER%20BL%20122%20BDL%209576.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CRISTAL%20CARTIER%20BL%20122%20BDL%209576.webp'], collection: 'Exotics & Exclusives', description: 'Cristal Cartier exotic surface.', color: 'Grey', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['grey', 'exotic'] },
    { id: 'ee-005', name: 'Crystal Soulages', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CRYSTAL%20SOULAGES%20BL%2028932%20BDL%20112364.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CRYSTAL%20SOULAGES%20BL%2028932%20BDL%20112364.webp'], collection: 'Exotics & Exclusives', description: 'Crystal Soulages exotic surface.', color: 'Mixed', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
    { id: 'ee-006', name: 'Crystalita Blue', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CRYSTALITA%20BLUE%20BL%2022640%20%20SL%2051-61.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/CRYSTALITA%20BLUE%20BL%2022640%20%20SL%2051-61.webp'], collection: 'Exotics & Exclusives', description: 'Crystalita Blue exotic surface.', color: 'Blue', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['blue', 'exotic'] },
    { id: 'ee-007', name: 'Fusion', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/FUSION%20BL%2027715%20BDL%20114171.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/FUSION%20BL%2027715%20BDL%20114171.webp'], collection: 'Exotics & Exclusives', description: 'Fusion exotic surface.', color: 'Mixed', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
    { id: 'ee-008', name: 'Hypnose', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/HYPNOSE%20%20BL%2027992%20BDL%20106874.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/HYPNOSE%20%20BL%2027992%20BDL%20106874.webp'], collection: 'Exotics & Exclusives', description: 'Hypnose exotic surface.', color: 'Mixed', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
    { id: 'ee-009', name: 'Laguna Crystal', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/LAGUNA%20CRYSTAL%20BL%2001-23%20BDL%2011090.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/LAGUNA%20CRYSTAL%20BL%2001-23%20BDL%2011090.webp'], collection: 'Exotics & Exclusives', description: 'Laguna Crystal exotic surface.', color: 'Grey', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['grey', 'exotic'] },
    { id: 'ee-010', name: 'Magma', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/MAGMA%20BL%203459%20SL%2029-39.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/MAGMA%20BL%203459%20SL%2029-39.webp'], collection: 'Exotics & Exclusives', description: 'Magma exotic surface.', color: 'Mixed', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
    { id: 'ee-011', name: 'Maori', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/MAORI%20BL%2021694%20BDL%201564334.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/MAORI%20BL%2021694%20BDL%201564334.webp'], collection: 'Exotics & Exclusives', description: 'Maori exotic surface.', color: 'Mixed', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
    { id: 'ee-012', name: 'Mirage Crystal Leather', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/MIRAGE%20CRYSTAL%20Leather%20BL%20467%20BDL%209414.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/MIRAGE%20CRYSTAL%20Leather%20BL%20467%20BDL%209414.webp'], collection: 'Exotics & Exclusives', description: 'Mirage Crystal Leather exotic surface.', color: 'Mixed', finish: 'Leather', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
    { id: 'ee-013', name: 'Volupia Maestro', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/VOLUPIA%20MAESTRO%20BL%2028153%20BDL%20114404.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/VOLUPIA%20MAESTRO%20BL%2028153%20BDL%20114404.webp'], collection: 'Exotics & Exclusives', description: 'Volupia Maestro exotic surface.', color: 'Mixed', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
    { id: 'ee-014', name: 'Vulkon', image: 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/VULKON%20BL%2029619%20BDL%20113977.webp', thumbnailImages: ['https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master/Exotics-Exclusives/VULKON%20BL%2029619%20BDL%20113977.webp'], collection: 'Exotics & Exclusives', description: 'Vulkon exotic surface.', color: 'Mixed', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['mixed', 'exotic'] },
  ],
  'granite-cutter-slabs-supplier': 
  [
    { id: 'gcss-001', name: 'Bengal White', image: '/assets/granite-cutter-slabs-supplier/BENGAL-WHITE-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/BENGAL-WHITE-1.png'], collection: 'Granite Cutter Slabs', description: 'Bengal White granite cutter slab.', color: 'White', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['white', 'granite'] },
    { id: 'gcss-002', name: 'Black Mariance', image: '/assets/granite-cutter-slabs-supplier/BLACK-MARIANCE-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/BLACK-MARIANCE-1.png'], collection: 'Granite Cutter Slabs', description: 'Black Mariance granite cutter slab.', color: 'Black', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['black', 'granite'] },
    { id: 'gcss-003', name: 'Coffee Brown', image: '/assets/granite-cutter-slabs-supplier/COFFEE-BROWN-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/COFFEE-BROWN-1.png'], collection: 'Granite Cutter Slabs', description: 'Coffee Brown granite cutter slab.', color: 'Brown', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['brown', 'granite'] },
    { id: 'gcss-004', name: 'Colonial White', image: '/assets/granite-cutter-slabs-supplier/COLONIAL-WHITE-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/COLONIAL-WHITE-1.png'], collection: 'Granite Cutter Slabs', description: 'Colonial White granite cutter slab.', color: 'White', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['white', 'granite'] },
    { id: 'gcss-005', name: 'Imperial Gold', image: '/assets/granite-cutter-slabs-supplier/IMPERIAL-GOLD-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/IMPERIAL-GOLD-1.png'], collection: 'Granite Cutter Slabs', description: 'Imperial Gold granite cutter slab.', color: 'Gold', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['gold', 'granite'] },
    { id: 'gcss-006', name: 'Kingfisher Blue', image: '/assets/granite-cutter-slabs-supplier/KINGFISHER-BLUE-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/KINGFISHER-BLUE-1.png'], collection: 'Granite Cutter Slabs', description: 'Kingfisher Blue granite cutter slab.', color: 'Blue', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['blue', 'granite'] },
    { id: 'gcss-007', name: 'Nova Black', image: '/assets/granite-cutter-slabs-supplier/NOVA-BLACK-50003CM120-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/NOVA-BLACK-50003CM120-1.png'], collection: 'Granite Cutter Slabs', description: 'Nova Black granite cutter slab.', color: 'Black', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['black', 'granite'] },
    { id: 'gcss-008', name: 'Romantic Red', image: '/assets/granite-cutter-slabs-supplier/ROMANTIC-RED-01-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/ROMANTIC-RED-01-1.png'], collection: 'Granite Cutter Slabs', description: 'Romantic Red granite cutter slab.', color: 'Red', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['red', 'granite'] },
    { id: 'gcss-009', name: 'Spice Black', image: '/assets/granite-cutter-slabs-supplier/SPICE-BLACK-01-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/SPICE-BLACK-01-1.png'], collection: 'Granite Cutter Slabs', description: 'Spice Black granite cutter slab.', color: 'Black', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['black', 'granite'] },
    { id: 'gcss-010', name: 'Thunder White', image: '/assets/granite-cutter-slabs-supplier/THUNDER-WHITE-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/THUNDER-WHITE-1.png'], collection: 'Granite Cutter Slabs', description: 'Thunder White granite cutter slab.', color: 'White', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['white', 'granite'] },
    { id: 'gcss-011', name: 'Titanium', image: '/assets/granite-cutter-slabs-supplier/TITANIUM-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/TITANIUM-1.png'], collection: 'Granite Cutter Slabs', description: 'Titanium granite cutter slab.', color: 'Grey', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['grey', 'granite'] },
    { id: 'gcss-012', name: 'Viscount White', image: '/assets/granite-cutter-slabs-supplier/VISCOUNT-WHITE-01-1.png', thumbnailImages: ['/assets/granite-cutter-slabs-supplier/VISCOUNT-WHITE-01-1.png'], collection: 'Granite Cutter Slabs', description: 'Viscount White granite cutter slab.', color: 'White', finish: 'Polished', useCase: ['Countertops', 'Flooring', 'Wall Cladding'], tags: ['white', 'granite'] },
  ],

  'quartzites': [
    { id: 'qz-001', name: 'Crystallo Classico', image: '/assets/QUARTZITES/CRYSTALLO CLASSICO .webp', thumbnailImages: ['/assets/QUARTZITES/CRYSTALLO CLASSICO .webp'], collection: 'Quartzites', description: 'Crystallo Classico quartzite with elegant crystalline patterns.', tags: ['quartzite', 'natural', 'premium'] },
    { id: 'qz-002', name: 'Crystallo Oro', image: '/assets/QUARTZITES/CRYSTALLO ORO.webp', thumbnailImages: ['/assets/QUARTZITES/CRYSTALLO ORO.webp'], collection: 'Quartzites', description: 'Crystallo Oro quartzite with golden shimmer.', tags: ['quartzite', 'gold', 'premium'] },
    { id: 'qz-003', name: 'Crystallo Verde', image: '/assets/QUARTZITES/CRYSTALLO VERDE .webp', thumbnailImages: ['/assets/QUARTZITES/CRYSTALLO VERDE .webp'], collection: 'Quartzites', description: 'Crystallo Verde quartzite with lush green tones.', tags: ['quartzite', 'green', 'premium'] },
    { id: 'qz-004', name: 'Crystallo White', image: '/assets/QUARTZITES/CRYSTALLO WHITE .webp', thumbnailImages: ['/assets/QUARTZITES/CRYSTALLO WHITE .webp'], collection: 'Quartzites', description: 'Crystallo White quartzite with pristine white surface.', tags: ['quartzite', 'white', 'premium'] },
    { id: 'qz-005', name: 'Fusion', image: '/assets/QUARTZITES/FUSION.webp', thumbnailImages: ['/assets/QUARTZITES/FUSION.webp'], collection: 'Quartzites', description: 'Fusion quartzite with dynamic mixed patterns.', tags: ['quartzite', 'mixed', 'premium'] },
    { id: 'qz-006', name: 'Glacier Blue', image: '/assets/QUARTZITES/GLACIER BLUE.webp', thumbnailImages: ['/assets/QUARTZITES/GLACIER BLUE.webp'], collection: 'Quartzites', description: 'Glacier Blue quartzite with icy blue tones.', tags: ['quartzite', 'blue', 'premium'] },
    { id: 'qz-007', name: 'Grey Father', image: '/assets/QUARTZITES/GREY FATHER.webp', thumbnailImages: ['/assets/QUARTZITES/GREY FATHER.webp'], collection: 'Quartzites', description: 'Grey Father quartzite with deep grey character.', tags: ['quartzite', 'grey', 'premium'] },
    { id: 'qz-008', name: 'Lava Oro', image: '/assets/QUARTZITES/LAVA ORO.webp', thumbnailImages: ['/assets/QUARTZITES/LAVA ORO.webp'], collection: 'Quartzites', description: 'Lava Oro quartzite with warm volcanic gold tones.', tags: ['quartzite', 'gold', 'premium'] },
    { id: 'qz-009', name: 'Majestic Grey', image: '/assets/QUARTZITES/MAJESTIC GREY.webp', thumbnailImages: ['/assets/QUARTZITES/MAJESTIC GREY.webp'], collection: 'Quartzites', description: 'Majestic Grey quartzite with regal grey finish.', tags: ['quartzite', 'grey', 'premium'] },
    { id: 'qz-010', name: 'Mango Fusion', image: '/assets/QUARTZITES/MANGO FUSION.webp', thumbnailImages: ['/assets/QUARTZITES/MANGO FUSION.webp'], collection: 'Quartzites', description: 'Mango Fusion quartzite with warm tropical hues.', tags: ['quartzite', 'mixed', 'premium'] },
    { id: 'qz-011', name: 'Metallic Blue', image: '/assets/QUARTZITES/METALLIC BLUE.webp', thumbnailImages: ['/assets/QUARTZITES/METALLIC BLUE.webp'], collection: 'Quartzites', description: 'Metallic Blue quartzite with shimmering blue metallic finish.', tags: ['quartzite', 'blue', 'premium'] },
    { id: 'qz-012', name: 'Pandora White', image: '/assets/QUARTZITES/PANDORA WHITE.webp', thumbnailImages: ['/assets/QUARTZITES/PANDORA WHITE.webp'], collection: 'Quartzites', description: 'Pandora White quartzite with elegant white surface.', tags: ['quartzite', 'white', 'premium'] },
    { id: 'qz-013', name: 'Patagonia Pink', image: '/assets/QUARTZITES/PATAGONIA PINK .webp', thumbnailImages: ['/assets/QUARTZITES/PATAGONIA PINK .webp'], collection: 'Quartzites', description: 'Patagonia Pink quartzite with subtle pink tones.', tags: ['quartzite', 'pink', 'premium'] },
  ],

  'granite': [
    { id: 'gr-001', name: 'Alaska Yellow', image: '/assets/GRANITE/ALASKA YELLOW.webp', thumbnailImages: ['/assets/GRANITE/ALASKA YELLOW.webp'], collection: 'Granite', description: 'Alaska Yellow granite with warm golden tones.', tags: ['granite', 'yellow', 'premium'] },
    { id: 'gr-002', name: 'Alpinus White', image: '/assets/GRANITE/ALPINUS WHITE.webp', thumbnailImages: ['/assets/GRANITE/ALPINUS WHITE.webp'], collection: 'Granite', description: 'Alpinus White granite with alpine white purity.', tags: ['granite', 'white', 'premium'] },
    { id: 'gr-003', name: 'Amazon White', image: '/assets/GRANITE/AMAZON WHITE.webp', thumbnailImages: ['/assets/GRANITE/AMAZON WHITE.webp'], collection: 'Granite', description: 'Amazon White granite with exotic white patterns.', tags: ['granite', 'white', 'premium'] },
    { id: 'gr-004', name: 'Arctic Blue', image: '/assets/GRANITE/ARCTIC BLUE.webp', thumbnailImages: ['/assets/GRANITE/ARCTIC BLUE.webp'], collection: 'Granite', description: 'Arctic Blue granite with cool blue tones.', tags: ['granite', 'blue', 'premium'] },
    { id: 'gr-005', name: 'Aspen White', image: '/assets/GRANITE/ASPEN WHITE.webp', thumbnailImages: ['/assets/GRANITE/ASPEN WHITE.webp'], collection: 'Granite', description: 'Aspen White granite with crisp white finish.', tags: ['granite', 'white', 'premium'] },
    { id: 'gr-006', name: 'Azul Nuevo', image: '/assets/GRANITE/AZUL NUEVO.webp', thumbnailImages: ['/assets/GRANITE/AZUL NUEVO.webp'], collection: 'Granite', description: 'Azul Nuevo granite with striking blue character.', tags: ['granite', 'blue', 'premium'] },
    { id: 'gr-007', name: 'Blue Dunes Gold', image: '/assets/GRANITE/BLUE DUNES GOLD (2).webp', thumbnailImages: ['/assets/GRANITE/BLUE DUNES GOLD (2).webp'], collection: 'Granite', description: 'Blue Dunes Gold granite with golden blue veining.', tags: ['granite', 'blue', 'gold'] },
    { id: 'gr-008', name: 'Blue Dunes', image: '/assets/GRANITE/BLUE DUNES.webp', thumbnailImages: ['/assets/GRANITE/BLUE DUNES.webp'], collection: 'Granite', description: 'Blue Dunes granite with oceanic blue patterns.', tags: ['granite', 'blue', 'premium'] },
    { id: 'gr-009', name: 'Blue Flower', image: '/assets/GRANITE/BLUE FLOWER.webp', thumbnailImages: ['/assets/GRANITE/BLUE FLOWER.webp'], collection: 'Granite', description: 'Blue Flower granite with floral blue accents.', tags: ['granite', 'blue', 'premium'] },
    { id: 'gr-010', name: 'Cafe Moca', image: '/assets/GRANITE/CAFE MOCA.webp', thumbnailImages: ['/assets/GRANITE/CAFE MOCA.webp'], collection: 'Granite', description: 'Cafe Moca granite with rich coffee-brown tones.', tags: ['granite', 'brown', 'premium'] },
    { id: 'gr-011', name: 'Calacatta D Oro', image: '/assets/GRANITE/Calacatta D Oro - Marble .webp', thumbnailImages: ['/assets/GRANITE/Calacatta D Oro - Marble .webp'], collection: 'Granite', description: 'Calacatta D Oro with luxurious golden veining.', tags: ['granite', 'white', 'gold'] },
    { id: 'gr-012', name: 'Champagne Rio', image: '/assets/GRANITE/Champagne Rio.webp', thumbnailImages: ['/assets/GRANITE/Champagne Rio.webp'], collection: 'Granite', description: 'Champagne Rio granite with sparkling champagne tones.', tags: ['granite', 'gold', 'premium'] },
    { id: 'gr-013', name: 'Desert Storm', image: '/assets/GRANITE/DESERT STORM.webp', thumbnailImages: ['/assets/GRANITE/DESERT STORM.webp'], collection: 'Granite', description: 'Desert Storm granite with warm sandy tones.', tags: ['granite', 'beige', 'premium'] },
    { id: 'gr-014', name: 'Equinox', image: '/assets/GRANITE/EQUINOX.webp', thumbnailImages: ['/assets/GRANITE/EQUINOX.webp'], collection: 'Granite', description: 'Equinox granite with balanced light and dark patterns.', tags: ['granite', 'mixed', 'premium'] },
    { id: 'gr-015', name: 'Forrester', image: '/assets/GRANITE/FORRESTER.webp', thumbnailImages: ['/assets/GRANITE/FORRESTER.webp'], collection: 'Granite', description: 'Forrester granite with natural forest-inspired tones.', tags: ['granite', 'green', 'premium'] },
    { id: 'gr-016', name: 'Galapagos', image: '/assets/GRANITE/GALAPAGOS.webp', thumbnailImages: ['/assets/GRANITE/GALAPAGOS.webp'], collection: 'Granite', description: 'Galapagos granite with exotic island-inspired patterns.', tags: ['granite', 'mixed', 'premium'] },
    { id: 'gr-017', name: 'Havana Blue', image: '/assets/GRANITE/HAVANA BLUE.webp', thumbnailImages: ['/assets/GRANITE/HAVANA BLUE.webp'], collection: 'Granite', description: 'Havana Blue granite with deep tropical blue.', tags: ['granite', 'blue', 'premium'] },
    { id: 'gr-018', name: 'Ice Cream', image: '/assets/GRANITE/ICE CREAM.webp', thumbnailImages: ['/assets/GRANITE/ICE CREAM.webp'], collection: 'Granite', description: 'Ice Cream granite with soft creamy tones.', tags: ['granite', 'cream', 'premium'] },
    { id: 'gr-019', name: 'Jasper Blue', image: '/assets/GRANITE/JASPER BLUE.webp', thumbnailImages: ['/assets/GRANITE/JASPER BLUE.webp'], collection: 'Granite', description: 'Jasper Blue granite with vibrant blue character.', tags: ['granite', 'blue', 'premium'] },
    { id: 'gr-020', name: 'Jasper Gold', image: '/assets/GRANITE/JASPER GOLD.webp', thumbnailImages: ['/assets/GRANITE/JASPER GOLD.webp'], collection: 'Granite', description: 'Jasper Gold granite with rich golden hues.', tags: ['granite', 'gold', 'premium'] },
    { id: 'gr-021', name: 'Libre', image: '/assets/GRANITE/LIBRE.webp', thumbnailImages: ['/assets/GRANITE/LIBRE.webp'], collection: 'Granite', description: 'Libre granite with free-flowing natural patterns.', tags: ['granite', 'mixed', 'premium'] },
    { id: 'gr-022', name: 'Marine Black', image: '/assets/GRANITE/MARINE BLACK.webp', thumbnailImages: ['/assets/GRANITE/MARINE BLACK.webp'], collection: 'Granite', description: 'Marine Black granite with deep oceanic black.', tags: ['granite', 'black', 'premium'] },
    { id: 'gr-023', name: 'Meridien', image: '/assets/GRANITE/MERIDIEN.webp', thumbnailImages: ['/assets/GRANITE/MERIDIEN.webp'], collection: 'Granite', description: 'Meridien granite with sophisticated meridian patterns.', tags: ['granite', 'mixed', 'premium'] },
    { id: 'gr-024', name: 'Monalisa', image: '/assets/GRANITE/MONALISA.webp', thumbnailImages: ['/assets/GRANITE/MONALISA.webp'], collection: 'Granite', description: 'Monalisa granite with artistic natural beauty.', tags: ['granite', 'mixed', 'premium'] },
    { id: 'gr-025', name: 'Sea Pearl', image: '/assets/GRANITE/SEA PEARL.webp', thumbnailImages: ['/assets/GRANITE/SEA PEARL.webp'], collection: 'Granite', description: 'Sea Pearl granite with lustrous pearl-like finish.', tags: ['granite', 'white', 'premium'] },
    { id: 'gr-026', name: 'Silver Ash', image: '/assets/GRANITE/SILVER ASH.webp', thumbnailImages: ['/assets/GRANITE/SILVER ASH.webp'], collection: 'Granite', description: 'Silver Ash granite with elegant silver-grey tones.', tags: ['granite', 'grey', 'premium'] },
    { id: 'gr-027', name: 'Snow Ridge', image: '/assets/GRANITE/SNOW RIDGE(1).webp', thumbnailImages: ['/assets/GRANITE/SNOW RIDGE(1).webp'], collection: 'Granite', description: 'Snow Ridge granite with crisp snow-white ridges.', tags: ['granite', 'white', 'premium'] },
    { id: 'gr-028', name: 'Spartacos', image: '/assets/GRANITE/SPARTACOS.webp', thumbnailImages: ['/assets/GRANITE/SPARTACOS.webp'], collection: 'Granite', description: 'Spartacos granite with bold warrior-like character.', tags: ['granite', 'mixed', 'premium'] },
  ],

  'marbles': [
    { id: 'mb-001', name: 'Balcan Grey', image: '/assets/Marbles/BALCAN GREY.webp', thumbnailImages: ['/assets/Marbles/BALCAN GREY.webp'], collection: 'Marbles', description: 'Balcan Grey marble with soft grey elegance.', tags: ['marble', 'grey', 'premium'] },
    { id: 'mb-002', name: 'Bardiglio', image: '/assets/Marbles/BARDIGLIO.webp', thumbnailImages: ['/assets/Marbles/BARDIGLIO.webp'], collection: 'Marbles', description: 'Bardiglio marble with Italian-inspired dark grey veining.', tags: ['marble', 'grey', 'premium'] },
    { id: 'mb-003', name: 'Belgia White', image: '/assets/Marbles/BELGIA WHITE.webp', thumbnailImages: ['/assets/Marbles/BELGIA WHITE.webp'], collection: 'Marbles', description: 'Belgia White marble with pure white beauty.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-004', name: 'Bianco Sula', image: '/assets/Marbles/BIANCO SULA .webp', thumbnailImages: ['/assets/Marbles/BIANCO SULA .webp'], collection: 'Marbles', description: 'Bianco Sula marble with pristine white finish.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-005', name: 'Botticino Classico', image: '/assets/Marbles/BOTTICINO CLASSICO.webp', thumbnailImages: ['/assets/Marbles/BOTTICINO CLASSICO.webp'], collection: 'Marbles', description: 'Botticino Classico marble with classic beige warmth.', tags: ['marble', 'beige', 'premium'] },
    { id: 'mb-006', name: 'Breccia Aurora', image: '/assets/Marbles/BRECCIA AUR0RA.webp', thumbnailImages: ['/assets/Marbles/BRECCIA AUR0RA.webp'], collection: 'Marbles', description: 'Breccia Aurora marble with warm aurora-inspired tones.', tags: ['marble', 'mixed', 'premium'] },
    { id: 'mb-007', name: 'Breccia Damascata', image: '/assets/Marbles/BRECCIA DAMASCATA.webp', thumbnailImages: ['/assets/Marbles/BRECCIA DAMASCATA.webp'], collection: 'Marbles', description: 'Breccia Damascata marble with exotic damascus patterns.', tags: ['marble', 'mixed', 'premium'] },
    { id: 'mb-008', name: 'Breccia Grey', image: '/assets/Marbles/BRECCIA GREY.webp', thumbnailImages: ['/assets/Marbles/BRECCIA GREY.webp'], collection: 'Marbles', description: 'Breccia Grey marble with distinguished grey patterns.', tags: ['marble', 'grey', 'premium'] },
    { id: 'mb-009', name: 'Brown Fantasy', image: '/assets/Marbles/BROWN FANTASY.webp', thumbnailImages: ['/assets/Marbles/BROWN FANTASY.webp'], collection: 'Marbles', description: 'Brown Fantasy marble with rich brown fantasy swirls.', tags: ['marble', 'brown', 'premium'] },
    { id: 'mb-010', name: 'Coastal Blue', image: '/assets/Marbles/COASTAL BLUE.webp', thumbnailImages: ['/assets/Marbles/COASTAL BLUE.webp'], collection: 'Marbles', description: 'Coastal Blue marble with serene coastal blue tones.', tags: ['marble', 'blue', 'premium'] },
    { id: 'mb-011', name: 'Fantasy White', image: '/assets/Marbles/FANTASY WHITE.webp', thumbnailImages: ['/assets/Marbles/FANTASY WHITE.webp'], collection: 'Marbles', description: 'Fantasy White marble with dreamy white patterns.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-012', name: 'Greenland', image: '/assets/Marbles/GREENLAND.webp', thumbnailImages: ['/assets/Marbles/GREENLAND.webp'], collection: 'Marbles', description: 'Greenland marble with lush green natural beauty.', tags: ['marble', 'green', 'premium'] },
    { id: 'mb-013', name: 'Honey Onyx', image: '/assets/Marbles/HONEY ONYX.webp', thumbnailImages: ['/assets/Marbles/HONEY ONYX.webp'], collection: 'Marbles', description: 'Honey Onyx marble with translucent golden warmth.', tags: ['marble', 'gold', 'premium'] },
    { id: 'mb-014', name: 'Indian Carrara White', image: '/assets/Marbles/INDIAN CARRARA WHITE.webp', thumbnailImages: ['/assets/Marbles/INDIAN CARRARA WHITE.webp'], collection: 'Marbles', description: 'Indian Carrara White marble with classic Carrara-inspired veining.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-015', name: 'Indian Statuario', image: '/assets/Marbles/INDIAN STATUARIO.webp', thumbnailImages: ['/assets/Marbles/INDIAN STATUARIO.webp'], collection: 'Marbles', description: 'Indian Statuario marble with premium Statuario character.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-016', name: 'Milano', image: '/assets/Marbles/MILANO.webp', thumbnailImages: ['/assets/Marbles/MILANO.webp'], collection: 'Marbles', description: 'Milano marble with sophisticated Italian design.', tags: ['marble', 'mixed', 'premium'] },
    { id: 'mb-017', name: 'Monalisa Classic', image: '/assets/Marbles/MONALISA CLASSIC .webp', thumbnailImages: ['/assets/Marbles/MONALISA CLASSIC .webp'], collection: 'Marbles', description: 'Monalisa Classic marble with timeless artistic beauty.', tags: ['marble', 'mixed', 'premium'] },
    { id: 'mb-018', name: 'Monalisa', image: '/assets/Marbles/MONALISA.1.webp', thumbnailImages: ['/assets/Marbles/MONALISA.1.webp'], collection: 'Marbles', description: 'Monalisa marble with artistic natural patterns.', tags: ['marble', 'mixed', 'premium'] },
    { id: 'mb-019', name: 'Panda White', image: '/assets/Marbles/PANDA WHITE.webp', thumbnailImages: ['/assets/Marbles/PANDA WHITE.webp'], collection: 'Marbles', description: 'Panda White marble with striking black and white contrast.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-020', name: 'River Blue', image: '/assets/Marbles/RIVER BLUE.webp', thumbnailImages: ['/assets/Marbles/RIVER BLUE.webp'], collection: 'Marbles', description: 'River Blue marble with flowing blue river patterns.', tags: ['marble', 'blue', 'premium'] },
    { id: 'mb-021', name: 'Savanna Grey', image: '/assets/Marbles/SAVANNA GREY.webp', thumbnailImages: ['/assets/Marbles/SAVANNA GREY.webp'], collection: 'Marbles', description: 'Savanna Grey marble with warm African grey tones.', tags: ['marble', 'grey', 'premium'] },
    { id: 'mb-022', name: 'Spider Grey', image: '/assets/Marbles/SPIDER GREY.webp', thumbnailImages: ['/assets/Marbles/SPIDER GREY.webp'], collection: 'Marbles', description: 'Spider Grey marble with web-like grey veining patterns.', tags: ['marble', 'grey', 'premium'] },
    { id: 'mb-023', name: 'Statuario', image: '/assets/Marbles/STATUARIO (2).webp', thumbnailImages: ['/assets/Marbles/STATUARIO (2).webp'], collection: 'Marbles', description: 'Statuario marble with iconic Italian veining.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-024', name: 'Statuario Extra', image: '/assets/Marbles/STATUARIO EXTRA.webp', thumbnailImages: ['/assets/Marbles/STATUARIO EXTRA.webp'], collection: 'Marbles', description: 'Statuario Extra marble with enhanced premium veining.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-025', name: 'Volacas White', image: '/assets/Marbles/VOLACAS WHITE (2).webp', thumbnailImages: ['/assets/Marbles/VOLACAS WHITE (2).webp'], collection: 'Marbles', description: 'Volacas White marble with Greek-inspired white beauty.', tags: ['marble', 'white', 'premium'] },
    { id: 'mb-026', name: 'Volacas White Classic', image: '/assets/Marbles/VOLACAS WHITE.webp', thumbnailImages: ['/assets/Marbles/VOLACAS WHITE.webp'], collection: 'Marbles', description: 'Volacas White Classic marble with timeless elegance.', tags: ['marble', 'white', 'premium'] },
  ],
  
};

// Helper function to get tiles for a specific collection
export const getTilesForCollection = (collectionName) => {
  const normalizedName = collectionName.toLowerCase().replace(/\s+/g, '-');
  return collectionTiles[normalizedName] || collectionTiles[collectionName.toLowerCase().replace(/\s+/g, '')] || [];
};

// Helper function to get product data for collection tiles
// For these new collections, each tile IS the product, so we return them directly
export const getCollectionTileProducts = (products, collectionName) => {
  const normalizedName = collectionName.toLowerCase().replace(/\s+/g, '-');
  const directTiles = collectionTiles[normalizedName];
  if (directTiles) return directTiles;

  // Fallback: look up by id in provided products array (legacy behaviour)
  const tiles = getTilesForCollection(collectionName);
  if (tiles.length > 0 && tiles[0].id && typeof tiles[0].id === 'number') {
    return products.filter(product =>
      tiles.some(tile => tile.id === product.id)
    );
  }
  return directTiles || [];
};
