// Collection-specific tiles configuration for ScrollStack component
// This file defines which specific products should be displayed as tiles for each collection

const BASE_URL = 'https://cdn.jsdelivr.net/gh/VipulSoniwork/madhav-surface-india-assets@master';

export const collectionTiles = {
  'regular-tiles': [
    {
      id: 'rt-001',
      name: 'Astoria',
      image: `${BASE_URL}/Regular-tiles-webp/ASTORIAA.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/ASTORIAA.webp`],
      collection: 'Regular Tiles',
      description: 'Natural granite tile with premium finish.',
      color: 'Mixed',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['granite', 'natural', 'premium'],
    },
    {
      id: 'rt-002',
      name: 'Bengal White',
      image: `${BASE_URL}/Regular-tiles-webp/BENGAL WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BENGAL WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Classic white Bengal granite with subtle patterning.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['white', 'granite', 'classic'],
    },
    {
      id: 'rt-003',
      name: 'Bianco Antico',
      image: `${BASE_URL}/Regular-tiles-webp/BIANCO ANTICO.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BIANCO ANTICO.webp`],
      collection: 'Regular Tiles',
      description: 'Elegant white granite with warm tones.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['white', 'granite', 'elegant'],
    },
    {
      id: 'rt-004',
      name: 'Bianco Tiffone',
      image: `${BASE_URL}/Regular-tiles-webp/BIANCO TIFFONE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BIANCO TIFFONE.webp`],
      collection: 'Regular Tiles',
      description: 'Bright white granite with fine grain texture.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['white', 'granite', 'bright'],
    },
    {
      id: 'rt-005',
      name: 'Black Forest',
      image: `${BASE_URL}/Regular-tiles-webp/BLACK FOREST.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BLACK FOREST.webp`],
      collection: 'Regular Tiles',
      description: 'Deep black granite with a forest-like natural pattern.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['black', 'granite', 'dark'],
    },
    {
      id: 'rt-006',
      name: 'Black Pearl',
      image: `${BASE_URL}/Regular-tiles-webp/BLACK PEARL.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/BLACK PEARL.webp`],
      collection: 'Regular Tiles',
      description: 'Lustrous black granite with pearl-like shimmer.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['black', 'granite', 'luxury'],
    },
    {
      id: 'rt-007',
      name: 'Coffee Brown',
      image: `${BASE_URL}/Regular-tiles-webp/COFFEE BROWN.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COFFEE BROWN.webp`],
      collection: 'Regular Tiles',
      description: 'Rich coffee brown granite for warm interiors.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops'],
      tags: ['brown', 'granite', 'warm'],
    },
    {
      id: 'rt-008',
      name: 'Colombo Juprana',
      image: `${BASE_URL}/Regular-tiles-webp/COLOMBO JUPRANA.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLOMBO JUPRANA.webp`],
      collection: 'Regular Tiles',
      description: 'Versatile Juprana granite from Colombo with mixed tones.',
      color: 'Mixed',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['granite', 'natural', 'mixed'],
    },
    {
      id: 'rt-009',
      name: 'Colonial Cream',
      image: `${BASE_URL}/Regular-tiles-webp/COLONIAL CREAM.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLONIAL CREAM.webp`],
      collection: 'Regular Tiles',
      description: 'Warm cream granite with colonial elegance.',
      color: 'Cream',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['cream', 'granite', 'warm'],
    },
    {
      id: 'rt-010',
      name: 'Colonial Gold',
      image: `${BASE_URL}/Regular-tiles-webp/COLONIAL GOLD.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLONIAL GOLD.webp`],
      collection: 'Regular Tiles',
      description: 'Golden granite with rich colonial character.',
      color: 'Gold',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['gold', 'granite', 'premium'],
    },
    {
      id: 'rt-011',
      name: 'Colonial White',
      image: `${BASE_URL}/Regular-tiles-webp/COLONIAL WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/COLONIAL WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Crisp white colonial granite for timeless spaces.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['white', 'granite', 'classic'],
    },
    {
      id: 'rt-012',
      name: 'Gibli Gold',
      image: `${BASE_URL}/Regular-tiles-webp/GIBLI GOLD.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/GIBLI GOLD.webp`],
      collection: 'Regular Tiles',
      description: 'Radiant gold granite with natural Gibli character.',
      color: 'Gold',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops'],
      tags: ['gold', 'granite', 'radiant'],
    },
    {
      id: 'rt-013',
      name: 'Gibli',
      image: `${BASE_URL}/Regular-tiles-webp/GIBLI.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/GIBLI.webp`],
      collection: 'Regular Tiles',
      description: 'Natural Gibli granite with organic patterns.',
      color: 'Mixed',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['granite', 'natural'],
    },
    {
      id: 'rt-014',
      name: 'Hassan Green',
      image: `${BASE_URL}/Regular-tiles-webp/HASSAN GREEN.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/HASSAN GREEN.webp`],
      collection: 'Regular Tiles',
      description: 'Distinctive green granite from Hassan, Karnataka.',
      color: 'Green',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['green', 'granite', 'unique'],
    },
    {
      id: 'rt-015',
      name: 'Himalayan Blue',
      image: `${BASE_URL}/Regular-tiles-webp/HIMALAYAN BLUE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/HIMALAYAN BLUE.webp`],
      collection: 'Regular Tiles',
      description: 'Rare blue granite inspired by the Himalayan range.',
      color: 'Blue',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['blue', 'granite', 'rare'],
    },
    {
      id: 'rt-016',
      name: 'Imperial Gold',
      image: `${BASE_URL}/Regular-tiles-webp/IMPERIAL GOLD.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/IMPERIAL GOLD.webp`],
      collection: 'Regular Tiles',
      description: 'Majestic gold granite for imperial interiors.',
      color: 'Gold',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['gold', 'granite', 'luxury'],
    },
    {
      id: 'rt-017',
      name: 'Imperial White',
      image: `${BASE_URL}/Regular-tiles-webp/IMPERIAL WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/IMPERIAL WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Pure white imperial granite with refined beauty.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['white', 'granite', 'premium'],
    },
    {
      id: 'rt-018',
      name: 'Indian Juprana 2',
      image: `${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA 2.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA 2.webp`],
      collection: 'Regular Tiles',
      description: 'Second variety of the popular Indian Juprana granite.',
      color: 'Mixed',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['granite', 'natural', 'indian'],
    },
    {
      id: 'rt-019',
      name: 'Indian Juprana',
      image: `${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/INDIAN JUPRANA.webp`],
      collection: 'Regular Tiles',
      description: 'Classic Indian Juprana granite with bold veining.',
      color: 'Mixed',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['granite', 'natural', 'indian'],
    },
    {
      id: 'rt-020',
      name: 'Ivory Brown',
      image: `${BASE_URL}/Regular-tiles-webp/IVORY BROWN.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/IVORY BROWN.webp`],
      collection: 'Regular Tiles',
      description: 'Soft ivory and brown granite with natural warmth.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['ivory', 'brown', 'granite'],
    },
    {
      id: 'rt-021',
      name: 'Kashmir Cream',
      image: `${BASE_URL}/Regular-tiles-webp/KASHMIR CREAM.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KASHMIR CREAM.webp`],
      collection: 'Regular Tiles',
      description: 'Creamy Kashmir granite with delicate mineral inclusions.',
      color: 'Cream',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops'],
      tags: ['cream', 'granite', 'kashmir'],
    },
    {
      id: 'rt-022',
      name: 'Kashmir Gold',
      image: `${BASE_URL}/Regular-tiles-webp/KASHMIR GOLD.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KASHMIR GOLD.webp`],
      collection: 'Regular Tiles',
      description: 'Royal gold Kashmir granite for luxurious surfaces.',
      color: 'Gold',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['gold', 'granite', 'kashmir'],
    },
    {
      id: 'rt-023',
      name: 'Kashmir White',
      image: `${BASE_URL}/Regular-tiles-webp/KASHMIR WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KASHMIR WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Pristine white Kashmir granite, globally renowned.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['white', 'granite', 'kashmir'],
    },
    {
      id: 'rt-024',
      name: 'Kuppam Green',
      image: `${BASE_URL}/Regular-tiles-webp/KUPPAM GREEN.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/KUPPAM GREEN.webp`],
      collection: 'Regular Tiles',
      description: 'Vibrant green granite from Kuppam, Andhra Pradesh.',
      color: 'Green',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['green', 'granite', 'vibrant'],
    },
    {
      id: 'rt-025',
      name: 'Matrix',
      image: `${BASE_URL}/Regular-tiles-webp/MATRIX.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MATRIX.webp`],
      collection: 'Regular Tiles',
      description: 'Dynamic matrix-patterned granite for modern spaces.',
      color: 'Mixed',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['granite', 'modern', 'unique'],
    },
    {
      id: 'rt-026',
      name: 'Meera White',
      image: `${BASE_URL}/Regular-tiles-webp/MEERA WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MEERA WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Soft white Meera granite with delicate patterns.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops'],
      tags: ['white', 'granite', 'soft'],
    },
    {
      id: 'rt-027',
      name: 'Mist Black',
      image: `${BASE_URL}/Regular-tiles-webp/MIST BLACK.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MIST BLACK.webp`],
      collection: 'Regular Tiles',
      description: 'Black granite with misty mineral highlights.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['black', 'granite', 'dark'],
    },
    {
      id: 'rt-028',
      name: 'Moon White',
      image: `${BASE_URL}/Regular-tiles-webp/MOON WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MOON WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Luminous white granite with moon-like texture.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops'],
      tags: ['white', 'granite', 'luminous'],
    },
    {
      id: 'rt-029',
      name: 'Multi Colour',
      image: `${BASE_URL}/Regular-tiles-webp/MULTI COLOUR.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/MULTI COLOUR.webp`],
      collection: 'Regular Tiles',
      description: 'Vibrant multi-colour granite for expressive designs.',
      color: 'Multi',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['multicolour', 'granite', 'vibrant'],
    },
    {
      id: 'rt-030',
      name: 'New Kashmir Cream',
      image: `${BASE_URL}/Regular-tiles-webp/NEW KASHMIR CREAM.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW KASHMIR CREAM.webp`],
      collection: 'Regular Tiles',
      description: 'Updated Kashmir Cream granite with refined texture.',
      color: 'Cream',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops'],
      tags: ['cream', 'granite', 'kashmir'],
    },
    {
      id: 'rt-031',
      name: 'New Kashmir Gold',
      image: `${BASE_URL}/Regular-tiles-webp/NEW KASHMIR GOLD.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW KASHMIR GOLD.webp`],
      collection: 'Regular Tiles',
      description: 'Contemporary Kashmir Gold granite with deep luster.',
      color: 'Gold',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['gold', 'granite', 'kashmir'],
    },
    {
      id: 'rt-032',
      name: 'New Kashmir White',
      image: `${BASE_URL}/Regular-tiles-webp/NEW KASHMIR WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW KASHMIR WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Refreshed Kashmir White granite, timelessly beautiful.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['white', 'granite', 'kashmir'],
    },
    {
      id: 'rt-033',
      name: 'New Meera White',
      image: `${BASE_URL}/Regular-tiles-webp/NEW MEERA WHITE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/NEW MEERA WHITE.webp`],
      collection: 'Regular Tiles',
      description: 'Upgraded Meera White granite with cleaner finish.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops'],
      tags: ['white', 'granite', 'meera'],
    },
    {
      id: 'rt-034',
      name: 'Paradiso Bash',
      image: `${BASE_URL}/Regular-tiles-webp/PARADISO BASH.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/PARADISO BASH.webp`],
      collection: 'Regular Tiles',
      description: 'Bold Paradiso Bash granite with striking purple tones.',
      color: 'Purple',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['purple', 'granite', 'paradiso'],
    },
    {
      id: 'rt-035',
      name: 'Paradiso Classic',
      image: `${BASE_URL}/Regular-tiles-webp/PARADISO CLASSIC.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/PARADISO CLASSIC.webp`],
      collection: 'Regular Tiles',
      description: 'Classic Paradiso granite with signature mineral patterns.',
      color: 'Purple',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['purple', 'granite', 'classic'],
    },
    {
      id: 'rt-036',
      name: 'Parana Boardux',
      image: `${BASE_URL}/Regular-tiles-webp/PARANA BOARDUX.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/PARANA BOARDUX.webp`],
      collection: 'Regular Tiles',
      description: 'Parana Boardux granite with distinctive grain.',
      color: 'Mixed',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['granite', 'natural', 'parana'],
    },
    {
      id: 'rt-037',
      name: 'Regal Black',
      image: `${BASE_URL}/Regular-tiles-webp/REGAL BLACK.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/REGAL BLACK.webp`],
      collection: 'Regular Tiles',
      description: 'Commanding Regal Black granite for sophisticated spaces.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['black', 'granite', 'regal'],
    },
    {
      id: 'rt-038',
      name: 'River White 1',
      image: `${BASE_URL}/Regular-tiles-webp/RIVER WHITE 1.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/RIVER WHITE 1.webp`],
      collection: 'Regular Tiles',
      description: 'Serene River White granite with flowing veins.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['white', 'granite', 'river'],
    },
    {
      id: 'rt-039',
      name: 'River White 2',
      image: `${BASE_URL}/Regular-tiles-webp/RIVER WHITE 2.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/RIVER WHITE 2.webp`],
      collection: 'Regular Tiles',
      description: 'Second variety of River White granite with unique flow.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['white', 'granite', 'river'],
    },
    {
      id: 'rt-040',
      name: 'Royal Ivory',
      image: `${BASE_URL}/Regular-tiles-webp/ROYAL IVORY.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/ROYAL IVORY.webp`],
      collection: 'Regular Tiles',
      description: 'Luxurious ivory granite fit for royal interiors.',
      color: 'Ivory',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['ivory', 'granite', 'luxury'],
    },
    {
      id: 'rt-041',
      name: 'Sapphire Blue',
      image: `${BASE_URL}/Regular-tiles-webp/SAPPHIRE BLUE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/SAPPHIRE BLUE.webp`],
      collection: 'Regular Tiles',
      description: 'Deep sapphire blue granite for elegant statements.',
      color: 'Blue',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['blue', 'granite', 'sapphire'],
    },
    {
      id: 'rt-042',
      name: 'Spice Black',
      image: `${BASE_URL}/Regular-tiles-webp/SPICE BLACK.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/SPICE BLACK.webp`],
      collection: 'Regular Tiles',
      description: 'Rich Spice Black granite with warm undertones.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['black', 'granite', 'spice'],
    },
    {
      id: 'rt-043',
      name: 'Steel Grey',
      image: `${BASE_URL}/Regular-tiles-webp/STEEL GREY.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/STEEL GREY.webp`],
      collection: 'Regular Tiles',
      description: 'Industrial-chic Steel Grey granite for modern aesthetics.',
      color: 'Grey',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['grey', 'granite', 'modern'],
    },
    {
      id: 'rt-044',
      name: 'Tan Brown',
      image: `${BASE_URL}/Regular-tiles-webp/TAN BROWN.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/TAN BROWN.webp`],
      collection: 'Regular Tiles',
      description: 'Warm Tan Brown granite with natural earthy tones.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['brown', 'granite', 'tan'],
    },
    {
      id: 'rt-045',
      name: 'Ultimate Black',
      image: `${BASE_URL}/Regular-tiles-webp/ULTIMATE BLACK.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/ULTIMATE BLACK.webp`],
      collection: 'Regular Tiles',
      description: 'Absolute deep black granite for bold design statements.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Flooring', 'Countertops', 'Wall Cladding'],
      tags: ['black', 'granite', 'bold'],
    },
    {
      id: 'rt-046',
      name: 'Viscount Waves',
      image: `${BASE_URL}/Regular-tiles-webp/VISCOUNT WAVES.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/VISCOUNT WAVES.webp`],
      collection: 'Regular Tiles',
      description: 'Elegant Viscount granite with wave-like natural patterns.',
      color: 'Grey',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding', 'Countertops'],
      tags: ['grey', 'granite', 'viscount'],
    },
    {
      id: 'rt-047',
      name: 'Vizag Blue',
      image: `${BASE_URL}/Regular-tiles-webp/VIZAG BLUE.webp`,
      thumbnailImages: [`${BASE_URL}/Regular-tiles-webp/VIZAG BLUE.webp`],
      collection: 'Regular Tiles',
      description: 'Striking Vizag Blue granite from Visakhapatnam.',
      color: 'Blue',
      finish: 'Polished',
      useCase: ['Flooring', 'Wall Cladding'],
      tags: ['blue', 'granite', 'vizag'],
    },
  ],

  'granite-slabs': [
    {
      id: 'gs-001',
      name: 'Absolute Black',
      image: `${BASE_URL}/Granite-Slabs/ABSOLUTE BLACK 4502,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/ABSOLUTE BLACK 4502,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'The definitive jet-black granite slab for premium installations.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['black', 'granite', 'absolute'],
    },
    {
      id: 'gs-002',
      name: 'Black Pearl',
      image: `${BASE_URL}/Granite-Slabs/BLACK PEARL 206,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/BLACK PEARL 206,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Black Pearl granite slab with iridescent mineral highlights.',
      color: 'Black',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['black', 'granite', 'pearl'],
    },
    {
      id: 'gs-003',
      name: 'Blue Pearl',
      image: `${BASE_URL}/Granite-Slabs/BLUE PEARL 4271,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/BLUE PEARL 4271,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Striking Blue Pearl granite slab with labradorite shimmer.',
      color: 'Blue',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['blue', 'granite', 'pearl'],
    },
    {
      id: 'gs-004',
      name: 'Coffee Brown',
      image: `${BASE_URL}/Granite-Slabs/COFFEE BROWN 111,3CM,10 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/COFFEE BROWN 111,3CM,10 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Rich Coffee Brown granite slab for warm interiors.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['brown', 'granite', 'coffee'],
    },
    {
      id: 'gs-005',
      name: 'Ivory Brown',
      image: `${BASE_URL}/Granite-Slabs/IVORY BROWN 799,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/IVORY BROWN 799,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Warm Ivory Brown granite slab with natural elegance.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['ivory', 'brown', 'granite'],
    },
    {
      id: 'gs-006',
      name: 'Kashmir Cream',
      image: `${BASE_URL}/Granite-Slabs/KASHMIR CREAM 1244,2CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/KASHMIR CREAM 1244,2CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Kerala\'s finest Kashmir Cream granite slab.',
      color: 'Cream',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['cream', 'granite', 'kashmir'],
    },
    {
      id: 'gs-007',
      name: 'Kuppam Green',
      image: `${BASE_URL}/Granite-Slabs/KUPPAM GREEN 103,2CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/KUPPAM GREEN 103,2CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Vibrant Kuppam Green granite slab with distinctive hue.',
      color: 'Green',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['green', 'granite', 'kuppam'],
    },
    {
      id: 'gs-008',
      name: 'Multi Colour',
      image: `${BASE_URL}/Granite-Slabs/MULTI COLOUR 3021,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/MULTI COLOUR 3021,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Bold multi-colour granite slab for expressive design.',
      color: 'Multi',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['multicolour', 'granite', 'vibrant'],
    },
    {
      id: 'gs-009',
      name: 'New Kashmir Cream',
      image: `${BASE_URL}/Granite-Slabs/NEW KASHMIR CREAM 2211,3CM,2 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW KASHMIR CREAM 2211,3CM,2 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Updated Kashmir Cream granite slab with enhanced finish.',
      color: 'Cream',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['cream', 'granite', 'kashmir'],
    },
    {
      id: 'gs-010',
      name: 'New Kashmir White',
      image: `${BASE_URL}/Granite-Slabs/NEW KASHMIR WHITE 536,3CM,40 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW KASHMIR WHITE 536,3CM,40 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'New Kashmir White granite slab with pure bright finish.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['white', 'granite', 'kashmir'],
    },
    {
      id: 'gs-011',
      name: 'New Meera White (Close Up)',
      image: `${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 104,3CM,30 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 104,3CM,30 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Close-up view of New Meera White granite slab.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['white', 'granite', 'meera'],
    },
    {
      id: 'gs-012',
      name: 'New Meera White',
      image: `${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 104,3CM,30.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 104,3CM,30.webp`],
      collection: 'Granite Slabs',
      description: 'Full slab view of New Meera White granite.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['white', 'granite', 'meera'],
    },
    {
      id: 'gs-013',
      name: 'New Meera White 91',
      image: `${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 91,3CM,10 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/NEW MEERA WHITE 91,3CM,10 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'New Meera White granite slab, variety 91.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring'],
      tags: ['white', 'granite', 'meera'],
    },
    {
      id: 'gs-014',
      name: 'Paradiso Bash',
      image: `${BASE_URL}/Granite-Slabs/PARADISO BASH 23A,3CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/PARADISO BASH 23A,3CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Paradiso Bash granite slab with rich purple undertones.',
      color: 'Purple',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['purple', 'granite', 'paradiso'],
    },
    {
      id: 'gs-015',
      name: 'Paradiso Classic',
      image: `${BASE_URL}/Granite-Slabs/PARADISO CLASSIC 1044,5CM,10 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/PARADISO CLASSIC 1044,5CM,10 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Paradiso Classic granite slab with signature veining.',
      color: 'Purple',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['purple', 'granite', 'classic'],
    },
    {
      id: 'gs-016',
      name: 'Sapphire Blue',
      image: `${BASE_URL}/Granite-Slabs/SAPPHIRE BLUE 1501,3CM,25 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/SAPPHIRE BLUE 1501,3CM,25 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Deep Sapphire Blue granite slab for elegant installations.',
      color: 'Blue',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['blue', 'granite', 'sapphire'],
    },
    {
      id: 'gs-017',
      name: 'Silver Waves',
      image: `${BASE_URL}/Granite-Slabs/SILVER WAVES 112,3CM,25 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/SILVER WAVES 112,3CM,25 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Silver Waves granite slab with shimmering wave patterns.',
      color: 'Grey',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['silver', 'grey', 'granite'],
    },
    {
      id: 'gs-018',
      name: 'Steel Grey',
      image: `${BASE_URL}/Granite-Slabs/STEEL GREY 307,2CM,15 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/STEEL GREY 307,2CM,15 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Sleek Steel Grey granite slab for contemporary spaces.',
      color: 'Grey',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['grey', 'granite', 'steel'],
    },
    {
      id: 'gs-019',
      name: 'Tan Brown',
      image: `${BASE_URL}/Granite-Slabs/TAN BROWN 101,3CM,25 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/TAN BROWN 101,3CM,25 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Warm Tan Brown granite slab with natural earthy tones.',
      color: 'Brown',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['brown', 'granite', 'tan'],
    },
    {
      id: 'gs-020',
      name: 'Viscount White',
      image: `${BASE_URL}/Granite-Slabs/VISCOUNT WHITE 1024,2CM,55 CLOSE UP.webp`,
      thumbnailImages: [`${BASE_URL}/Granite-Slabs/VISCOUNT WHITE 1024,2CM,55 CLOSE UP.webp`],
      collection: 'Granite Slabs',
      description: 'Viscount White granite slab with flowing crystalline patterns.',
      color: 'White',
      finish: 'Polished',
      useCase: ['Countertops', 'Flooring', 'Wall Cladding'],
      tags: ['white', 'grey', 'granite'],
    },
  ],
};

// Helper function to get tiles for a specific collection
export const getTilesForCollection = (collectionName) => {
  const normalizedName = collectionName.toLowerCase().replace(/\s+/g, '-');
  return collectionTiles[normalizedName] || collectionTiles[collectionName.toLowerCase().replace(/\s+/g, '')] || [];
};

// Helper function to get product data for collection tiles
// For these new collections, each tile IS the product, so we return them directly
export const getCollectionTileProducts = (products, collectionName) => {
  const normalizedName = collectionName.toLowerCase().replace(/\s+/g, '-');
  const directTiles = collectionTiles[normalizedName];
  if (directTiles) return directTiles;

  // Fallback: look up by id in provided products array (legacy behaviour)
  const tiles = getTilesForCollection(collectionName);
  if (tiles.length > 0 && tiles[0].id && typeof tiles[0].id === 'number') {
    return products.filter(product =>
      tiles.some(tile => tile.id === product.id)
    );
  }
  return directTiles || [];
};
